name:                Functional-Neural-Network
version:             0.1.0.0
github:              "nifets/Functional-Neural-Network"
license:             BSD3
author:              "Stefan Manolache"
maintainer:          "stefanmanol@gmail.com"
copyright:           "2020 Stefan Manolache"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nifets/Functional-Neural-Network#readme>

dependencies:
- base >= 4.7 && < 5
- matrix
- normaldistribution
- random
- random-shuffle
- csv

library:
  source-dirs: src

executables:
  Neural-Network-exe:
    main:                Main.hs
    source-dirs:         app/main
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Functional-Neural-Network

  XorTest-exe:
    main:                Main.hs
    source-dirs:         app/xor
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Functional-Neural-Network
